# Site settings
author: Darrel Castellano
title: Darrel's Blog
header-img: img/home-bg.png
email: dcastellano2007@gmail.com
copyright_name: Darrel Castellano
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DarrelJames

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
